export const OBTENER_CLIENTES = "OBTENER CLIENTES";
export const REGISTRAR_CLIENTE = "REGISTRAR CLIENTE";
export const OBTENER_CLIENTE = "OBTENER CLIENTE";
export const MODIFICAR_CLIENTE = "MODIFICAR CLIENTE";
export const ELIMINAR_CLIENTE = "ELIMINAR CLIENTE";
